import {getCorrectConstant} from '../Core/ActionConstants';

export const ACTION_CONSTANTS = {
	SIGNIN_STATUS: "SIGNIN_STATUS",
	RESTORE_TOKEN: "RESTORE_TOKEN",
	USER_DASHBOARD_DATA:"USER_DASHBOARD_DATA",
	USER_CONTACTS:"USER_CONTACTS",
	ADD_USER_IN_EVENT:"ADD_USER_IN_EVENT",
	REMOVE_USER_IN_EVENT:"REMOVE_USER_IN_EVENT",
	LIST_WEEK_EXPENSES: "LIST_WEEK_EXPENSES",
	GET_WEEK_EXPENSES: "GET_WEEK_EXPENSES",
	CHECK_ACTIVITY_LOADER: "CHECK_ACTIVITY_LOADER",
	CHECK_ACTIVITY_MESSAGE: "CHECK_ACTIVITY_MESSAGE",
	CHECK_ACTIVITY_ERROR: "CHECK_ACTIVITY_ERROR",
	GET_SWIPING_ENABLED: "GET_SWIPING_ENABLED",
	GET_EVENT_LIST:"GET_EVENT_LIST",
	GET_START_END_DATE:"GET_START_END_DATE",
	GET_EVENT_DATA: "GET_EVENT_DATA",
	GET_EVENT_EXPENSES: "GET_EVENT_EXPENSES",
	RECENT_EXPENSES_LIST: "RECENT_EXPENSES_LIST",
	THIS_MONTH_EXPENSES_LIST: "THIS_MONTH_EXPENSES_LIST",
	LAST_MONTH_EXPENSES_LIST: "LAST_MONTH_EXPENSES_LIST",
	EMPTY_THIS_MONTH_EXPENSES: "EMPTY_THIS_MONTH_EXPENSES",
	EMPTY_LAST_MONTH_EXPENSES: "EMPTY_LAST_MONTH_EXPENSES",
	GET_EXPECTED_CATEGORY_DATA: "GET_EXPECTED_CATEGORY_DATA",
	ENTERED_ACTIVITY_MESSAGE: "ENTERED_ACTIVITY_MESSAGE"
};

export const ENV_CONSTANTS = {
	LOGIN_IMAGE: 'LOGIN_IMAGE',
	ONE_SIGNAL_ID_DEV: 'ONE_SIGNAL_ID_DEV',
	ONE_SIGNAL_ID_PROD: 'ONE_SIGNAL_ID_PROD'
}
